In [2]:
import IPython, nussl, numpy as np, scipy as sp, matplotlib.pyplot as plt, matplotlib, sklearn, librosa, cmath,math,time,vamp
import os
from IPython.display import Audio, display
from scipy.fftpack import fft, ifft

from sklearn.neighbors import KNeighborsClassifier

In [5]:
### CONTROL ###
X = [[0], [1], [2], [3]] #training
y = [0, 0, 1, 1] #testing

nn_control = KNeighborsClassifier(n_neighbors=3)
nn_control.fit(X, y) 


print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))

[0]
[[ 0.66666667  0.33333333]]


In [7]:
### HPSS - Harmonic ###
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]

nn_hpss_harmonic = KNeighborsClassifier(n_neighbors=3)
nn_hpss_harmonic.fit(X, y) 


print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))

[0]
[[ 0.66666667  0.33333333]]


In [8]:
### HPSS - Percussive ###
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]

nn_hpss_percussive = KNeighborsClassifier(n_neighbors=3)
nn_hpss_percussive.fit(X, y) 


print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))

[0]
[[ 0.66666667  0.33333333]]


In [9]:
### REPET - Foreground ###
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]

nn_repet_foreground = KNeighborsClassifier(n_neighbors=3)
nn_repet_foreground.fit(X, y) 


print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))

[0]
[[ 0.66666667  0.33333333]]


In [11]:
### REPET - Background ###
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]

nn_repet_background = KNeighborsClassifier(n_neighbors=3)
nn_repet_background.fit(X, y) 

print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))

[0]
[[ 0.66666667  0.33333333]]
